### ISSUE TITLE
Design variation for MP delta mini V1

### ISSUE THREAD

**Issue by abinmahfuth** [fablabbcn/aei-kit-impresion-pasta#1]
Hi all,

Many thanks for the inspiring design. I have the MP delta mini V1 and made a new nozzle design to fit that printer, I hope if you share more people will benefit. More details about the assembly will follow.

You can find it here: 
https://github.com/abinmahfuth/aei-kit-impression-paste-MP-Delta

**Comment by oscgonfer** [comment]
Hi @abinmahfuth 

Nice! Do you want to maybe [create a Pull Request on the repo](https://github.com/fablabbcn/aei-kit-impresion-pasta/compare) so that your design is also in the same repo?

**Comment by abinmahfuth** [comment]
Hi @oscgonfer, 

Thanks for your response, I just did create a Pull request :)
